#!/bin/sh

pwd=`pwd`
docdir=`echo $pwd | sed -e "s#/code/#/doc/#"`

if [ "$#" = "0" ]; then
    echo "need argument \"compile\", \"execute\" or \"doc\""
fi

case $1 in
    compile) javac -classpath $pwd/.. *.java ;;
    execute) echo "Remember to input expression as command argument, e.g.:, 2+3*3"
             java -classpath $pwd/..:$pwd/. Main $2 ;;
    doc) rm -r -f $docdir;
	 mkdir -m 755 -p $docdir;
	 javadoc -d $docdir -private -classpath . *.java ;;
esac

