#!/bin/sh

pwd=`pwd`
docdir=`echo $pwd | sed -e "s#/code/#/doc/#"`

if [ "$#" = "0" ]; then
    echo "need argument \"compile\", \"execute\" or \"doc\""
fi

case $1 in
    compile) cd $pwd/editor; javac -classpath .. *.java ;
             cd $pwd/cmdpack; javac -classpath .. *.java ;
             cd $pwd; javac -classpath . *.java ;;
    execute) appletviewer Main.html ;;
    doc) rm -r -f $docdir;
	 mkdir -m 755 -p $docdir;
	 javadoc -d $docdir -private -classpath . *.java editor cmdpack ;;
esac

