#!/bin/sh

pwd=`pwd`
docdir=`echo $pwd | sed -e "s#/code/#/doc/#"`

if [ "$#" = "0" ]; then
    echo "need argument \"compile\", \"test\" or \"doc\""
fi

CLASSPATH=$pwd/../..:/home/antoy/local/junit3.2/junit.jar

case $1 in
    compile) javac -classpath $CLASSPATH -Xlint:unchecked *.java ;;
    # test) cd ../..; java -classpath $CLASSPATH pattpack/pooledlist/ListTest ;;
    doc) rm -r -f $docdir;
	 mkdir -m 755 -p $docdir;
         cd ../..
	 javadoc -d $docdir -private -classpath  $CLASSPATH pattpack.pooledlist ;;
esac

