#!/bin/sh

pwd=`pwd`
docdir=`echo $pwd | sed -e "s#/code/#/doc/#"`

if [ "$#" = "0" ]; then
    echo "need argument \"compile\" or \"doc\""
fi

case $1 in
    compile) javac *.java ;;
    doc) rm -r -f $docdir;
	 mkdir -m 755 -p $docdir;
	 javadoc -d $docdir *.java ;;
esac

