#!/bin/sh
# Tue Oct  5 21:19:46 PDT 1999

suffix=`date  | awk '{print $2, $3, $4}' | tr " :" "-"`

cd ..
zip -r exercises-$suffix exercises
zip -d exercises-$suffix exercises/doc/\*
ls -lt exercises-$suffix.zip
