#!/bin/sh

pwd=`pwd`
docdir=`echo $pwd | sed -e "s#/code/#/doc/#"`

if [ "$#" = "0" ]; then
    echo "need argument \"compile\" or \"doc\""
fi

case $1 in
    compile) javac -classpath $pwd/../.. *.java ;;
    doc) rm -r -f $docdir;
	 mkdir -m 755 -p $docdir;
         cd ../..
	 javadoc -d $docdir -private -classpath $pwd/../..  pattpack.token_3 ;;
esac

